# Generated by Django 5.0.6 on 2024-07-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproyecto', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='proyectos/')),
                ('tecnologias', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('T', 'Terminado')], default='P', max_length=1)),
            ],
        ),
    ]
